In [1]:
words = open('/home/risal/X3s4c5/Makemore/names.txt','r').read().splitlines()

In [2]:
len(words), words

(32033,
 ['emma',
  'olivia',
  'ava',
  'isabella',
  'sophia',
  'charlotte',
  'mia',
  'amelia',
  'harper',
  'evelyn',
  'abigail',
  'emily',
  'elizabeth',
  'mila',
  'ella',
  'avery',
  'sofia',
  'camila',
  'aria',
  'scarlett',
  'victoria',
  'madison',
  'luna',
  'grace',
  'chloe',
  'penelope',
  'layla',
  'riley',
  'zoey',
  'nora',
  'lily',
  'eleanor',
  'hannah',
  'lillian',
  'addison',
  'aubrey',
  'ellie',
  'stella',
  'natalie',
  'zoe',
  'leah',
  'hazel',
  'violet',
  'aurora',
  'savannah',
  'audrey',
  'brooklyn',
  'bella',
  'claire',
  'skylar',
  'lucy',
  'paisley',
  'everly',
  'anna',
  'caroline',
  'nova',
  'genesis',
  'emilia',
  'kennedy',
  'samantha',
  'maya',
  'willow',
  'kinsley',
  'naomi',
  'aaliyah',
  'elena',
  'sarah',
  'ariana',
  'allison',
  'gabriella',
  'alice',
  'madelyn',
  'cora',
  'ruby',
  'eva',
  'serenity',
  'autumn',
  'adeline',
  'hailey',
  'gianna',
  'valentina',
  'isla',
  'eliana',
  'quinn',

In [3]:
min(len(w) for w in words)

2

In [4]:
max(len(w) for w in words)

15

In [5]:
b = {}
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs,chs[1:]):
        biagram = (ch1, ch2)
        b[biagram] = b.get(biagram, 0) + 1

In [6]:
sorted(b.items(), key= lambda kv: -kv[1])

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [7]:
import torch

In [8]:
N = torch.zeros((27,27), dtype = torch.int32)

In [9]:
N.shape

torch.Size([27, 27])

In [10]:
chars = sorted(list(set(''.join(words))))

In [11]:
stoi = {s:i+1 for i ,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}


In [12]:
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [13]:
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1

In [14]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [15]:
p = N[0].float() # creating the probability from the numbers or count
p = p /p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [16]:
P = (N+1).float() # To addresss problem of 0 turning to inf.makeing model smoother by adding up 1 so no combination gives inf while log operation  
P /= P.sum(1, keepdims= True) ## Addressing the keepdims for not happining the broadcasting errors [27, 27]  / [27, 1] 

In [17]:
g  = torch.Generator().manual_seed(123)
for i in range(5):
    ix = 0
    out = []
    while True:
        p = P[ix]
        ix = torch.multinomial(p, num_samples = 1, replacement = True, generator = g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))

ayl.
eeieahviannalizyr.
pidouyra.
jon.
cerrdyanaya.


In [18]:
probs = P[ix1, ix2]

In [19]:
likelihood = 0.0 # Log-likelihood
count = 0 
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        probs = P[ix1, ix2]
        logprob = torch.log(probs)
        count += 1
        likelihood += logprob
        print(f'{ch1}{ch2}: {probs:.4f},{logprob=}')
nnl = -likelihood 
print(f"{likelihood=}")
print(f"{nnl=}")
print(f"average_neg_loglikelihood: {nnl / count}")

.e: 0.0478,logprob=tensor(-3.0410)
em: 0.0377,logprob=tensor(-3.2793)
mm: 0.0253,logprob=tensor(-3.6753)
ma: 0.3885,logprob=tensor(-0.9454)
a.: 0.1958,logprob=tensor(-1.6305)
.o: 0.0123,logprob=tensor(-4.3965)
ol: 0.0779,logprob=tensor(-2.5526)
li: 0.1774,logprob=tensor(-1.7293)
iv: 0.0152,logprob=tensor(-4.1845)
vi: 0.3508,logprob=tensor(-1.0476)
ia: 0.1380,logprob=tensor(-1.9807)
a.: 0.1958,logprob=tensor(-1.6305)
.a: 0.1376,logprob=tensor(-1.9835)
av: 0.0246,logprob=tensor(-3.7041)
va: 0.2473,logprob=tensor(-1.3971)
a.: 0.1958,logprob=tensor(-1.6305)
likelihood=tensor(-38.8086)
nnl=tensor(38.8086)
average_neg_loglikelihood: 2.4255354404449463


In [20]:
# loading the dataset 
xs, ys = [], []
for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [21]:
xs 

tensor([ 0,  5, 13, 13,  1])

In [22]:
ys 

tensor([ 5, 13, 13,  1,  0])

In [23]:
import torch.nn.functional as F
xenc = F.one_hot(xs, num_classes=27).float()
xenc

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
xenc.shape

torch.Size([5, 27])

In [25]:
W = torch.randn(27,27)
logits = (xenc @ W)
logits

tensor([[ 0.8962, -0.6895,  0.0870, -0.4815, -0.4760, -0.3746,  0.3043, -0.0539,
          0.1787,  1.4475,  0.0698,  1.5632, -0.6660,  1.0570,  0.3870,  0.9323,
         -1.7269,  0.0515, -0.2805, -0.7866, -0.7027,  0.5445, -0.0589,  0.2545,
          2.4673, -0.3635, -0.3381],
        [ 0.8087, -0.1806, -0.8381, -0.0444,  0.8832, -0.0618, -0.6940, -2.2366,
          0.9317, -1.5683, -1.0953,  0.3288, -0.6699,  0.6988, -1.1698, -0.1488,
         -1.2186,  0.8390, -1.4766,  0.2911,  0.5178,  2.2106,  0.8056, -0.3873,
          0.7203,  0.0677,  0.1428],
        [ 2.4360, -1.1380,  1.1238,  1.2234,  0.9187, -1.9544, -1.2568, -0.2164,
         -0.3633,  1.1238, -0.5278, -0.3965, -0.0595, -1.2038, -0.0315, -0.8057,
         -0.5505, -1.2067, -0.9529, -0.2400,  0.4028, -1.9269, -1.4383,  0.1199,
         -0.2814, -1.0446, -0.8989],
        [ 2.4360, -1.1380,  1.1238,  1.2234,  0.9187, -1.9544, -1.2568, -0.2164,
         -0.3633,  1.1238, -0.5278, -0.3965, -0.0595, -1.2038, -0.0315, -0.8057

In [26]:
counts = logits.exp() 
counts

tensor([[ 2.4502,  0.5018,  1.0909,  0.6179,  0.6213,  0.6875,  1.3556,  0.9476,
          1.1956,  4.2524,  1.0723,  4.7743,  0.5138,  2.8777,  1.4726,  2.5405,
          0.1778,  1.0528,  0.7554,  0.4554,  0.4953,  1.7237,  0.9428,  1.2898,
         11.7904,  0.6952,  0.7131],
        [ 2.2449,  0.8348,  0.4325,  0.9566,  2.4185,  0.9400,  0.4996,  0.1068,
          2.5388,  0.2084,  0.3344,  1.3893,  0.5118,  2.0113,  0.3104,  0.8617,
          0.2956,  2.3140,  0.2284,  1.3379,  1.6784,  9.1211,  2.2380,  0.6789,
          2.0549,  1.0700,  1.1535],
        [11.4272,  0.3205,  3.0764,  3.3988,  2.5060,  0.1417,  0.2846,  0.8054,
          0.6953,  3.0764,  0.5899,  0.6727,  0.9422,  0.3001,  0.9690,  0.4468,
          0.5767,  0.2992,  0.3856,  0.7866,  1.4960,  0.1456,  0.2373,  1.1274,
          0.7548,  0.3518,  0.4070],
        [11.4272,  0.3205,  3.0764,  3.3988,  2.5060,  0.1417,  0.2846,  0.8054,
          0.6953,  3.0764,  0.5899,  0.6727,  0.9422,  0.3001,  0.9690,  0.4468

In [27]:
probs = counts / counts.sum(1, keepdims = True)
probs

tensor([[0.0521, 0.0107, 0.0232, 0.0131, 0.0132, 0.0146, 0.0288, 0.0201, 0.0254,
         0.0904, 0.0228, 0.1014, 0.0109, 0.0611, 0.0313, 0.0540, 0.0038, 0.0224,
         0.0161, 0.0097, 0.0105, 0.0366, 0.0200, 0.0274, 0.2505, 0.0148, 0.0152],
        [0.0579, 0.0215, 0.0112, 0.0247, 0.0624, 0.0242, 0.0129, 0.0028, 0.0655,
         0.0054, 0.0086, 0.0358, 0.0132, 0.0519, 0.0080, 0.0222, 0.0076, 0.0597,
         0.0059, 0.0345, 0.0433, 0.2353, 0.0577, 0.0175, 0.0530, 0.0276, 0.0298],
        [0.3155, 0.0088, 0.0849, 0.0938, 0.0692, 0.0039, 0.0079, 0.0222, 0.0192,
         0.0849, 0.0163, 0.0186, 0.0260, 0.0083, 0.0268, 0.0123, 0.0159, 0.0083,
         0.0106, 0.0217, 0.0413, 0.0040, 0.0066, 0.0311, 0.0208, 0.0097, 0.0112],
        [0.3155, 0.0088, 0.0849, 0.0938, 0.0692, 0.0039, 0.0079, 0.0222, 0.0192,
         0.0849, 0.0163, 0.0186, 0.0260, 0.0083, 0.0268, 0.0123, 0.0159, 0.0083,
         0.0106, 0.0217, 0.0413, 0.0040, 0.0066, 0.0311, 0.0208, 0.0097, 0.0112],
        [0.0444, 0.0190,

In [28]:
probs.shape

torch.Size([5, 27])

In [29]:
loss = -probs[torch.arange(5),ys].log().mean()
loss

tensor(3.9640)

In [34]:
# loading the dataset 
xs, ys = [], []
for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [35]:
g = torch.Generator().manual_seed(123)
W = torch.randn((27,27),generator = g, requires_grad = True)

In [36]:
for i in range(100):
    # Feed - Forward
    xenc = F.one_hot(xs, num_classes=27).float()
    logits = (xenc @ W)
    counts = logits.exp() 
    probs = counts / counts.sum(1, keepdims = True)
    loss = -probs[torch.arange(5),ys].log().mean() + 0.01 * (W**2).mean() # The last elements added is regularization term
    print(f"For {i} {loss=}")
    
    # Backward
    W.grad = None 
    loss.backward()
    
    # Optimizer update 
    W.data += -0.5 * W.grad


For 0 loss=tensor(3.3952, grad_fn=<AddBackward0>)
For 1 loss=tensor(3.3040, grad_fn=<AddBackward0>)
For 2 loss=tensor(3.2142, grad_fn=<AddBackward0>)
For 3 loss=tensor(3.1258, grad_fn=<AddBackward0>)
For 4 loss=tensor(3.0387, grad_fn=<AddBackward0>)
For 5 loss=tensor(2.9530, grad_fn=<AddBackward0>)
For 6 loss=tensor(2.8686, grad_fn=<AddBackward0>)
For 7 loss=tensor(2.7857, grad_fn=<AddBackward0>)
For 8 loss=tensor(2.7041, grad_fn=<AddBackward0>)
For 9 loss=tensor(2.6240, grad_fn=<AddBackward0>)
For 10 loss=tensor(2.5453, grad_fn=<AddBackward0>)
For 11 loss=tensor(2.4681, grad_fn=<AddBackward0>)
For 12 loss=tensor(2.3924, grad_fn=<AddBackward0>)
For 13 loss=tensor(2.3182, grad_fn=<AddBackward0>)
For 14 loss=tensor(2.2456, grad_fn=<AddBackward0>)
For 15 loss=tensor(2.1746, grad_fn=<AddBackward0>)
For 16 loss=tensor(2.1053, grad_fn=<AddBackward0>)
For 17 loss=tensor(2.0376, grad_fn=<AddBackward0>)
For 18 loss=tensor(1.9716, grad_fn=<AddBackward0>)
For 19 loss=tensor(1.9073, grad_fn=<AddBa

In [37]:
g  = torch.Generator().manual_seed(123)
for i in range(5):
    ix = 0
    out = []
    while True:
        # p = P[ix]
        
        xenc = F.one_hot(torch.tensor([ix]), num_classes=27).float()
        logits = (xenc @ W)
        counts = logits.exp() 
        p = counts / counts.sum(1, keepdims = True)
        ix = torch.multinomial(p, num_samples = 1, replacement = True, generator = g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))

emmanwia.
evtyqlmma.
emmmmmauyyftiqdwolvrdha.
ema.
ema.
